# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cc360 < Formula
  desc "Terminal UI for browsing and resuming Claude Code sessions"
  homepage "https://github.com/achton/cc360"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/achton/cc360/releases/download/v0.4.0/cc360_0.4.0_darwin_amd64.tar.gz"
      sha256 "27a21569286c020d70361c7169dcf873c3f96b421c3477f68a403a447286cd21"

      define_method(:install) do
        bin.install "cc360"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/achton/cc360/releases/download/v0.4.0/cc360_0.4.0_darwin_arm64.tar.gz"
      sha256 "24a194832dc30c3749330f9b1e33648ca72dbf3675cfe3eab595246d209b1e80"

      define_method(:install) do
        bin.install "cc360"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/achton/cc360/releases/download/v0.4.0/cc360_0.4.0_linux_amd64.tar.gz"
      sha256 "db09d8c544b696d82e18e10523a4044ccd8b5bdefa4e98bf59cb97bf6d4d5ed8"
      define_method(:install) do
        bin.install "cc360"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/achton/cc360/releases/download/v0.4.0/cc360_0.4.0_linux_arm64.tar.gz"
      sha256 "79dd72942864824f4d43574b584f3a9ee0326cdaf043a3d081fef8233b752784"
      define_method(:install) do
        bin.install "cc360"
      end
    end
  end
end
