# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cc360 < Formula
  desc "Terminal UI for browsing and resuming Claude Code sessions"
  homepage "https://github.com/achton/cc360"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/achton/cc360/releases/download/v0.1.0/cc360_0.1.0_darwin_amd64.tar.gz"
      sha256 "9c1809ab34e7913489e6aaa1611fba1ba60da9a0cdfdbe1b37e33f2cb318207a"

      define_method(:install) do
        bin.install "cc360"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/achton/cc360/releases/download/v0.1.0/cc360_0.1.0_darwin_arm64.tar.gz"
      sha256 "f4cd7eba5e196c90f98f7f39a9e7ccfb32df0e4491514264154e7f189e2f8659"

      define_method(:install) do
        bin.install "cc360"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/achton/cc360/releases/download/v0.1.0/cc360_0.1.0_linux_amd64.tar.gz"
      sha256 "3aa895b52f5608296c5ed9ac229256cdc8ba37ecedf4b10b8a1a79b3eee55cf8"
      define_method(:install) do
        bin.install "cc360"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/achton/cc360/releases/download/v0.1.0/cc360_0.1.0_linux_arm64.tar.gz"
      sha256 "c12b99abbb3569e84214a8b374fc013b3bea6ac44a6365ed1d5be92652917027"
      define_method(:install) do
        bin.install "cc360"
      end
    end
  end
end
