# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cc360 < Formula
  desc "Terminal UI for browsing and resuming Claude Code sessions"
  homepage "https://github.com/achton/cc360"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/achton/cc360/releases/download/v0.2.4/cc360_0.2.4_darwin_amd64.tar.gz"
      sha256 "bbad4f76aff9dee02219f8576c782c77d7a7f2db0347622907d1976778cff24e"

      define_method(:install) do
        bin.install "cc360"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/achton/cc360/releases/download/v0.2.4/cc360_0.2.4_darwin_arm64.tar.gz"
      sha256 "dbebf7d364d150d094e7b83a5cb968f997ac5aab68013f0dc5485257b7e9fd51"

      define_method(:install) do
        bin.install "cc360"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/achton/cc360/releases/download/v0.2.4/cc360_0.2.4_linux_amd64.tar.gz"
      sha256 "1f2f1a18800f81c4cb35c71106097236326b5828b8af750bf1ad2316e3a52caf"
      define_method(:install) do
        bin.install "cc360"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/achton/cc360/releases/download/v0.2.4/cc360_0.2.4_linux_arm64.tar.gz"
      sha256 "6bf65b06760f6d80af94e93ea42a7784fe4abcaa82a316570919a06ad63a7a7d"
      define_method(:install) do
        bin.install "cc360"
      end
    end
  end
end
