# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc360" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "de1851fd9485371e5329a0e914f0a10118a36a683879133e93462ea5c871b2df"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eea56ee47a4f3504ded40057964688b71d72b801eeda0233b720655e71aeb4b3"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99b96005f01f35fd6b7a7474c0e331e13a8403efec4a979c46fe117e505f8476"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "72932a67dc5dde75ba0130ae11dbbf25d82d4bad61bc397eb9a4fee0fff2f1cb"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc360"
  desc "Terminal UI for browsing and resuming Claude Code sessions"
  homepage "https://github.com/achton/cc360"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc360"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc360"]
    end
  end

  # No zap stanza required

end
