# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc360" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "050c4e9d86cb37e9df3962cf4bbeeb7c2009078a3599ef1249bf0b25a6d15991"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c76b63d02ea652fb16b6dee00fc36f95998c51fd80ee97269d789ca343409f75"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8dcb00b99b917c197eb6b200813fe0acbd2ac5e2b434751b4ae8a83efadf7568"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5fa8438253a5755e4e60fa82e70413f28f2377b96ca954166cb75e8aef73580b"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cc360"
  desc "Terminal UI for browsing and resuming Claude Code sessions"
  homepage "https://github.com/achton/cc360"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc360"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc360"]
    end
  end

  # No zap stanza required
end
