# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc360" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "f6d8c358041cbe0d6e6875897f998aae95286a757851dd9d3adf8e3abfb86ec2"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "836b1b0603592cc32b41f83c7ebfafe46a441d6b74c1f9bee4497b755c917a51"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee4ec98eca38576241167bc57e81c07cb9fdee0c7f80bce4ff4e8193b569671f"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e7c2542cd19c6d600c984d2af84a7f507e44e881282bfc601e919c534083f6f"
      url "https://github.com/achton/cc360/releases/download/v#{version}/cc360_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cc360"
  desc "Terminal UI for browsing and resuming Claude Code sessions"
  homepage "https://github.com/achton/cc360"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc360"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc360"]
    end
  end

  # No zap stanza required

end
